/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

export type { HealingRecipe } from './types';

export {
    searchInputRecipe,
    cartIconRecipe,
    userIconRecipe,
    userMenuLogoutButtonRecipe,
    navMenuRecipe,
    categoryLinksRecipe,
    megaMenuContainerRecipe,
    mobileMenuToggleRecipe,
    footerRecipe,
    footerLinksRecipe,
    loadingSpinnerRecipe,
    errorMessageRecipe,
    sfccCookiesRecipe,
} from './storefront.recipes';

export {
    productTilesRecipe,
    productImagesRecipe,
    productTitlesRecipe,
    productPricesRecipe,
    productGridRecipe,
    moreOptionsButtonRecipe,
} from './product-listing.recipes';

export {
    productTitlePdpRecipe,
    productPricePdpRecipe,
    variantGroupsRecipe,
    variantLinksRecipe,
    variantButtonsRecipe,
    variantDropdownsRecipe,
    quantityInputRecipe,
    addToCartButtonRecipe,
    miniCartDrawerRecipe,
} from './product-detail.recipes';

export {
    cartItemsRecipe,
    itemTitleCartRecipe,
    itemQuantityCartRecipe,
    itemPriceCartRecipe,
    checkoutButtonRecipe,
    emptyCartMessageRecipe,
} from './cart.recipes';

export {
    firstNameInputRecipe,
    lastNameInputRecipe,
    emailInputRecipe,
    passwordInputRecipe,
    confirmPasswordInputRecipe,
    createAccountButtonRecipe,
    signInLinkRecipe,
    trackingConsentBannerRecipe,
    acceptTrackingButtonRecipe,
    declineTrackingButtonRecipe,
} from './signup.recipes';

export {
    emailInputLoginRecipe,
    passwordInputLoginRecipe,
    signInButtonRecipe,
    forgotPasswordLinkRecipe,
    signUpLinkLoginRecipe,
    continueWithAppleButtonRecipe,
    continueWithGoogleButtonRecipe,
} from './login.recipes';

export {
    pageTitleRecipe,
    profileCardRecipe,
    profileEditButtonRecipe,
    profileFormRecipe,
    firstNameFieldRecipe,
    lastNameFieldRecipe,
    emailFieldRecipe,
    phoneFieldRecipe,
    genderSelectRecipe,
    birthdayFieldRecipe,
    profileSaveButtonRecipe,
    profileCancelButtonRecipe,
    passwordCardRecipe,
    changePasswordButtonRecipe,
    passwordFormRecipe,
    currentPasswordFieldRecipe,
    newPasswordFieldRecipe,
    confirmPasswordFieldRecipe,
    passwordSaveButtonRecipe,
    passwordCancelButtonRecipe,
    passwordCheckIconRecipe,
    passwordXIconRecipe,
    successToastRecipe,
    errorToastRecipe,
    formErrorRecipe,
    accountDetailsRecipes,
} from './account-details.recipes';

export {
    orderListPageTitleRecipe,
    orderListPageSubtitleRecipe,
    orderCardRecipe,
    orderCardFirstRecipe,
    orderDateRecipe,
    orderTotalRecipe,
    orderItemsRecipe,
    orderStatusRecipe,
    viewDetailsLinkRecipe,
    orderListSkeletonRecipe,
    emptyStateMessageRecipe,
    totalOrdersTextRecipe,
    orderListRecipes,
} from './order-list.recipes';

export {
    addressesPageTitleRecipe,
    addNewAddressButtonRecipe,
    emptyStateMessageRecipe as emptyStateMessageAddressesRecipe,
    addressCardsRecipe,
    defaultBadgeRecipe,
    editAddressButtonRecipe,
    removeAddressButtonRecipe,
    setDefaultButtonRecipe,
    addressDialogRecipe,
    dialogTitleRecipe,
    addressIdFieldRecipe,
    firstNameFieldRecipe as firstNameFieldAddressesRecipe,
    lastNameFieldRecipe as lastNameFieldAddressesRecipe,
    phoneFieldRecipe as phoneFieldAddressesRecipe,
    countryCodeSelectRecipe,
    address1FieldRecipe,
    address2FieldRecipe,
    cityFieldRecipe,
    stateCodeSelectRecipe,
    postalCodeFieldRecipe,
    preferredCheckboxRecipe,
    saveAddressButtonRecipe,
    cancelButtonRecipe as cancelButtonAddressesRecipe,
    deleteDialogRecipe,
    confirmDeleteButtonRecipe,
    cancelDeleteButtonRecipe,
    successToastAddressesRecipe,
    errorToastAddressesRecipe,
    formErrorAddressesRecipe,
    accountAddressesRecipes,
} from './account-addresses.recipes';

export {
    passkeysPageTitleRecipe,
    addPasskeyButtonRecipe,
    passkeyDeleteButtonsRecipe,
    emptyStateMessageRecipe as emptyStateMessagePasskeysRecipe,
    deletePasskeyDialogRecipe,
    passkeyRegistrationModalRecipe,
    accountPasskeysRecipes,
} from './account-passkeys.recipes';

export {
    backToOrdersLinkRecipe,
    orderDetailsPageTitleRecipe,
    orderNumberRecipe,
    orderStatusBadgeRecipe,
    shippingStatusBadgeRecipe,
    itemsOrderedHeadingRecipe,
    shipmentContainerRecipe,
    orderItemRecipe,
    shippingAddressCardRecipe,
    trackingNumberCardRecipe,
    orderSummaryHeadingRecipe,
    orderSummaryCardRecipe,
    orderSkeletonRecipe,
    orderNotFoundCardRecipe,
    backToOrderHistoryButtonRecipe,
    orderSectionRecipe,
    orderDetailsRecipes,
} from './order-details.recipes';

export {
    passkeyModalRecipe,
    passkeyNameInputRecipe,
    passkeyNameContinueButtonRecipe,
    passkeyOtpInputsRecipe,
    passkeyErrorMessageRecipe,
    passkeyVerifyingStatusRecipe,
    passkeyResendButtonRecipe,
    passkeyUpsellToastRecipe,
    passkeyUpsellToastActionRecipe,
    passkeySuccessToastRecipe,
    passkeyRegistrationRecipes,
} from './passkey-registration.recipes';

import type { HealingRecipe } from './types';
import {
    searchInputRecipe,
    cartIconRecipe,
    userIconRecipe,
    userMenuLogoutButtonRecipe,
    navMenuRecipe,
    categoryLinksRecipe,
    megaMenuContainerRecipe,
    mobileMenuToggleRecipe,
    footerRecipe,
    footerLinksRecipe,
    loadingSpinnerRecipe,
    errorMessageRecipe,
} from './storefront.recipes';
import {
    productTilesRecipe,
    productImagesRecipe,
    productTitlesRecipe,
    productPricesRecipe,
    productGridRecipe,
    moreOptionsButtonRecipe,
} from './product-listing.recipes';
import {
    productTitlePdpRecipe,
    productPricePdpRecipe,
    variantGroupsRecipe,
    variantLinksRecipe,
    variantButtonsRecipe,
    variantDropdownsRecipe,
    quantityInputRecipe,
    addToCartButtonRecipe,
    miniCartDrawerRecipe,
} from './product-detail.recipes';
import {
    cartItemsRecipe,
    itemTitleCartRecipe,
    itemQuantityCartRecipe,
    itemPriceCartRecipe,
    checkoutButtonRecipe,
    emptyCartMessageRecipe,
} from './cart.recipes';
import {
    firstNameInputRecipe,
    lastNameInputRecipe,
    emailInputRecipe,
    passwordInputRecipe,
    confirmPasswordInputRecipe,
    createAccountButtonRecipe,
    signInLinkRecipe,
    trackingConsentBannerRecipe,
    acceptTrackingButtonRecipe,
    declineTrackingButtonRecipe,
} from './signup.recipes';
import {
    emailInputLoginRecipe,
    passwordInputLoginRecipe,
    signInButtonRecipe,
    forgotPasswordLinkRecipe,
    signUpLinkLoginRecipe,
    continueWithAppleButtonRecipe,
    continueWithGoogleButtonRecipe,
} from './login.recipes';
import {
    pageTitleRecipe,
    profileCardRecipe,
    profileEditButtonRecipe,
    profileFormRecipe,
    firstNameFieldRecipe,
    lastNameFieldRecipe,
    emailFieldRecipe,
    phoneFieldRecipe,
    genderSelectRecipe,
    birthdayFieldRecipe,
    profileSaveButtonRecipe,
    profileCancelButtonRecipe,
    verifyEmailButtonRecipe,
    changeEmailButtonRecipe,
    emailVerifiedBadgeRecipe,
    emailUnverifiedBadgeRecipe,
    otpModalRecipe,
    otpResendButtonRecipe,
    emailUpdateFormRecipe,
    passwordCardRecipe,
    changePasswordButtonRecipe,
    passwordFormRecipe,
    currentPasswordFieldRecipe,
    newPasswordFieldRecipe,
    confirmPasswordFieldRecipe,
    passwordSaveButtonRecipe,
    passwordCancelButtonRecipe,
    passwordCheckIconRecipe,
    passwordXIconRecipe,
    successToastRecipe,
    errorToastRecipe,
    formErrorRecipe,
} from './account-details.recipes';
import {
    orderListPageTitleRecipe,
    orderListPageSubtitleRecipe,
    orderCardRecipe,
    orderCardFirstRecipe,
    orderDateRecipe,
    orderTotalRecipe,
    orderItemsRecipe,
    orderStatusRecipe,
    viewDetailsLinkRecipe,
    orderListSkeletonRecipe,
    emptyStateMessageRecipe,
    totalOrdersTextRecipe,
} from './order-list.recipes';
import {
    backToOrdersLinkRecipe,
    orderDetailsPageTitleRecipe,
    orderNumberRecipe,
    orderStatusBadgeRecipe,
    shippingStatusBadgeRecipe,
    itemsOrderedHeadingRecipe,
    shipmentContainerRecipe,
    orderItemRecipe,
    shippingAddressCardRecipe,
    trackingNumberCardRecipe,
    orderSummaryHeadingRecipe,
    orderSummaryCardRecipe,
    orderSkeletonRecipe,
    orderNotFoundCardRecipe,
    backToOrderHistoryButtonRecipe,
    orderSectionRecipe,
} from './order-details.recipes';
import {
    addressesPageTitleRecipe,
    addNewAddressButtonRecipe,
    addressCardsRecipe,
    defaultBadgeRecipe,
    editAddressButtonRecipe,
    removeAddressButtonRecipe,
    setDefaultButtonRecipe,
    addressDialogRecipe,
    dialogTitleRecipe,
    addressIdFieldRecipe,
    countryCodeSelectRecipe,
    address1FieldRecipe,
    address2FieldRecipe,
    cityFieldRecipe,
    stateCodeSelectRecipe,
    postalCodeFieldRecipe,
    preferredCheckboxRecipe,
    saveAddressButtonRecipe,
    deleteDialogRecipe,
    confirmDeleteButtonRecipe,
    cancelDeleteButtonRecipe,
    successToastAddressesRecipe,
    errorToastAddressesRecipe,
    formErrorAddressesRecipe,
} from './account-addresses.recipes';
import {
    passkeyModalRecipe,
    passkeyNameInputRecipe,
    passkeyNameContinueButtonRecipe,
    passkeyOtpInputsRecipe,
    passkeyErrorMessageRecipe,
    passkeyVerifyingStatusRecipe,
    passkeyResendButtonRecipe,
    passkeyUpsellToastRecipe,
    passkeyUpsellToastActionRecipe,
    passkeySuccessToastRecipe,
} from './passkey-registration.recipes';
import {
    passkeysPageTitleRecipe,
    addPasskeyButtonRecipe,
    passkeyDeleteButtonsRecipe,
    emptyStateMessageRecipe as emptyStateMessagePasskeysRecipe,
    deletePasskeyDialogRecipe,
    passkeyRegistrationModalRecipe,
} from './account-passkeys.recipes';

export const healingRecipes: HealingRecipe[] = [
    // Storefront / header / navigation
    searchInputRecipe,
    cartIconRecipe,
    userIconRecipe,
    userMenuLogoutButtonRecipe,
    navMenuRecipe,
    categoryLinksRecipe,
    megaMenuContainerRecipe,
    mobileMenuToggleRecipe,
    footerRecipe,
    footerLinksRecipe,
    loadingSpinnerRecipe,
    errorMessageRecipe,
    // Product listing
    productTilesRecipe,
    productImagesRecipe,
    productTitlesRecipe,
    productPricesRecipe,
    productGridRecipe,
    moreOptionsButtonRecipe,
    // Product detail page
    productTitlePdpRecipe,
    productPricePdpRecipe,
    variantGroupsRecipe,
    variantLinksRecipe,
    variantButtonsRecipe,
    variantDropdownsRecipe,
    quantityInputRecipe,
    addToCartButtonRecipe,
    miniCartDrawerRecipe,
    // Cart
    cartItemsRecipe,
    itemTitleCartRecipe,
    itemPriceCartRecipe,
    itemQuantityCartRecipe,
    checkoutButtonRecipe,
    emptyCartMessageRecipe,
    // Signup
    firstNameInputRecipe,
    lastNameInputRecipe,
    emailInputRecipe,
    passwordInputRecipe,
    confirmPasswordInputRecipe,
    createAccountButtonRecipe,
    signInLinkRecipe,
    trackingConsentBannerRecipe,
    acceptTrackingButtonRecipe,
    declineTrackingButtonRecipe,
    // Login
    emailInputLoginRecipe,
    passwordInputLoginRecipe,
    signInButtonRecipe,
    forgotPasswordLinkRecipe,
    signUpLinkLoginRecipe,
    continueWithAppleButtonRecipe,
    continueWithGoogleButtonRecipe,
    // Account details
    pageTitleRecipe,
    profileCardRecipe,
    profileEditButtonRecipe,
    profileFormRecipe,
    firstNameFieldRecipe,
    lastNameFieldRecipe,
    emailFieldRecipe,
    phoneFieldRecipe,
    genderSelectRecipe,
    birthdayFieldRecipe,
    profileSaveButtonRecipe,
    profileCancelButtonRecipe,
    // Email verification
    verifyEmailButtonRecipe,
    changeEmailButtonRecipe,
    emailVerifiedBadgeRecipe,
    emailUnverifiedBadgeRecipe,
    otpModalRecipe,
    otpResendButtonRecipe,
    emailUpdateFormRecipe,
    // Password
    passwordCardRecipe,
    changePasswordButtonRecipe,
    passwordFormRecipe,
    currentPasswordFieldRecipe,
    newPasswordFieldRecipe,
    confirmPasswordFieldRecipe,
    passwordSaveButtonRecipe,
    passwordCancelButtonRecipe,
    passwordCheckIconRecipe,
    passwordXIconRecipe,
    successToastRecipe,
    errorToastRecipe,
    formErrorRecipe,
    // Order list
    orderListPageTitleRecipe,
    orderListPageSubtitleRecipe,
    orderCardRecipe,
    orderCardFirstRecipe,
    orderDateRecipe,
    orderTotalRecipe,
    orderItemsRecipe,
    orderStatusRecipe,
    viewDetailsLinkRecipe,
    orderListSkeletonRecipe,
    emptyStateMessageRecipe,
    totalOrdersTextRecipe,
    // Order details
    backToOrdersLinkRecipe,
    orderDetailsPageTitleRecipe,
    orderNumberRecipe,
    orderStatusBadgeRecipe,
    shippingStatusBadgeRecipe,
    itemsOrderedHeadingRecipe,
    shipmentContainerRecipe,
    orderItemRecipe,
    shippingAddressCardRecipe,
    trackingNumberCardRecipe,
    orderSummaryHeadingRecipe,
    orderSummaryCardRecipe,
    orderSkeletonRecipe,
    orderNotFoundCardRecipe,
    backToOrderHistoryButtonRecipe,
    orderSectionRecipe,
    // Account addresses
    addressesPageTitleRecipe,
    addNewAddressButtonRecipe,
    addressCardsRecipe,
    defaultBadgeRecipe,
    editAddressButtonRecipe,
    removeAddressButtonRecipe,
    setDefaultButtonRecipe,
    addressDialogRecipe,
    dialogTitleRecipe,
    addressIdFieldRecipe,
    countryCodeSelectRecipe,
    address1FieldRecipe,
    address2FieldRecipe,
    cityFieldRecipe,
    stateCodeSelectRecipe,
    postalCodeFieldRecipe,
    preferredCheckboxRecipe,
    saveAddressButtonRecipe,
    deleteDialogRecipe,
    confirmDeleteButtonRecipe,
    cancelDeleteButtonRecipe,
    successToastAddressesRecipe,
    errorToastAddressesRecipe,
    formErrorAddressesRecipe,
    // Passkey registration
    passkeyModalRecipe,
    passkeyNameInputRecipe,
    passkeyNameContinueButtonRecipe,
    passkeyOtpInputsRecipe,
    passkeyErrorMessageRecipe,
    passkeyVerifyingStatusRecipe,
    passkeyResendButtonRecipe,
    passkeyUpsellToastRecipe,
    passkeyUpsellToastActionRecipe,
    passkeySuccessToastRecipe,
    // Account passkeys
    passkeysPageTitleRecipe,
    addPasskeyButtonRecipe,
    passkeyDeleteButtonsRecipe,
    emptyStateMessagePasskeysRecipe,
    deletePasskeyDialogRecipe,
    passkeyRegistrationModalRecipe,
];

export default healingRecipes;
