/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Relative paths required here — this file is evaluated by vite-node during
// react-router typegen (via routes.ts), before Vite aliases are resolved.
import { defineConfig, defaultSecurityHeaders } from '@salesforce/storefront-next-runtime/config';
import type { Config } from './src/types/config';
import { TrackingConsent } from './src/types/tracking-consent';
// Auto-generated by `pnpm config:aggregate-extensions` from each extension's config.ts.
// Merging it into app.extension is what makes PUBLIC__app__extension__* env paths valid and
// reachable via useConfig() — without it those overrides are dropped as unknown config paths.
// The path is explicit to `config/index.ts`: a bare `./src/extensions/config` resolves to the
// sibling `config.json` extension registry, not this barrel. Relative (not the `@/` alias) —
// see the top-of-file note on vite-node/typegen.
import generatedExtensionConfig from './src/extensions/config/index';
// Auto-generated by `pnpm config:aggregate-extensions` (same prestep that produces the
// client barrel above — the CLI runs both modes via Promise.all) from each extension's
// server-config.ts. Merged into app.serverExtension below; values are reachable via
// getConfig(context) on the server only. The client config extractor (src/lib/app-config-client.ts)
// strips serverExtension before window.__APP_CONFIG__, and a Vite plugin fails the build if
// any client chunk imports this barrel. There is intentionally no PUBLIC__ override path —
// the AST validator forbids process.env, so server-only secrets must be read from process.env
// in a route handler.
import generatedServerExtensionConfig from './src/extensions/config/server';

/**
 * Application Configuration
 *
 * This file defines the default configuration for the application.
 * All values can be overridden using PUBLIC__ prefixed environment variables.
 * Environment Variable Convention:
 *
 * Use PUBLIC__ prefix with double underscore (__) path separators:
 *    - PUBLIC__app__commerce__api__clientId → app.commerce.api.clientId
 *    - PUBLIC__app__site__locale → app.site.locale
 *    - PUBLIC__app__pages__cart__quantityUpdateDebounce → app.pages.cart.quantityUpdateDebounce
 *    - PUBLIC__app__pages__cart__showLineItemDescription → app.pages.cart.showLineItemDescription
 *    - PUBLIC__app__site__features__socialLogin__providers=["Apple","Google"] → app.features.socialLogin.providers
 *
 * The PUBLIC__ prefix indicates these values are SAFE TO EXPOSE to the client.
 * They get bundled into window.__APP_CONFIG__ and are accessible in browser code.
 *
 * Server-only secrets (API keys, passwords, etc.) should NEVER use this config system.
 * Read them directly from process.env in server-side code (loaders, actions, middleware).
 *
 * Documentation:
 *    - Configuration Guide: `docs/README-CONFIG.md`
 *    - Configuration Options Reference: `docs/README-CONFIG-OPTIONS.md`
 */

// DIS hosts:
// - Staging: https://edge.disstg.commercecloud.salesforce.com
// - Production: https://edge.dis.commercecloud.salesforce.com
const DIS_DEFAULT_HOST = 'https://edge.disstg.commercecloud.salesforce.com';

export default defineConfig<Config>(
    {
        // Project identification and metadata
        // See CONFIG-OPTIONS.md#metadata for detailed documentation
        metadata: {
            projectName: 'Storefront Next Retail App',
            projectSlug: 'storefront-next-retail-app',
        },
        // Runtime deployment settings for Managed Runtime (server-only)
        // See CONFIG-OPTIONS.md#runtime for detailed documentation
        runtime: {
            // MRT deployment settings (server-only, set via MRT_PROJECT and MRT_TARGET env vars)
            defaultMrtProject: '',
            defaultMrtTarget: '',
            ssrOnly: [],
            ssrShared: [],
            ssrParameters: {
                ssrFunctionNodeVersion: '24.x',
                // envBasePath can be used to configure Managed Runtime environment to add basepath
                // See BASE-PATH.md for more details
                envBasePath: '',
            },
        },
        // Main application configuration (public settings)
        // See CONFIG-OPTIONS.md#app for complete reference
        app: {
            // Page-specific configuration
            // See CONFIG-OPTIONS.md#pages for detailed documentation
            pages: {
                navigation: {
                    rootCategoryId: 'root',
                    maxDepth: 2,
                },
                home: {
                    featuredProductsCount: 12,
                },
                cart: {
                    quantityUpdateDebounce: 750,
                    enableRemoveConfirmation: true,
                    maxQuantityPerItem: 999,
                    enableSaveForLater: false,
                    removeAction: '/action/cart-item-remove',
                    ruleBasedProductLimit: 50,
                    showLineItemDescription: false,
                    miniCart: {
                        enableViewCartButton: true,
                    },
                },
                search: {
                    placeholder: 'Search',
                    enableSearchSuggestions: true,
                    maxSuggestions: 8,
                    enableRecentSearches: true,
                    suggestionsDebounce: 400,
                },
                maintenancePage: {
                    sharedMaintenancePage: true,
                    cdnUrl: 'https://prd.cmp.cdn.commercecloud.salesforce.com',
                    forwardedHost: '',
                },
            },
            // Commerce Cloud API integration
            // See CONFIG-OPTIONS.md#commerce for detailed documentation
            commerce: {
                api: {
                    // Commerce Cloud API credentials (required, set via env vars)
                    clientId: '',
                    organizationId: '',
                    shortCode: '',
                    // Optional API settings
                    proxy: '/mobify/proxy/api',
                    // OAuth2 redirect_uri sent to SLAS — must match what's registered in SLAS Admin.
                    // Not a storefront route; token exchange happens server-side with redirect: 'manual'.
                    callback: '/callback',
                    privateKeyEnabled: false,
                    registeredRefreshTokenExpirySeconds: undefined,
                    guestRefreshTokenExpirySeconds: undefined,
                },
                // Site context configuration
                // Each site can have its own locale, currency, and detection settings
                sites: [
                    {
                        id: 'RefArchGlobal',
                        defaultLocale: 'en-GB',
                        defaultCurrency: 'GBP',
                        supportedLocales: [
                            {
                                id: 'en-GB',
                                preferredCurrency: 'GBP',
                            },
                            {
                                id: 'da-DK',
                                preferredCurrency: 'DKK',
                            },
                            {
                                id: 'de-DE',
                                preferredCurrency: 'EUR',
                            },
                            {
                                id: 'fi-FI',
                                preferredCurrency: 'EUR',
                            },
                            {
                                id: 'fr-FR',
                                preferredCurrency: 'EUR',
                            },
                            {
                                id: 'it-IT',
                                preferredCurrency: 'EUR',
                            },
                            {
                                id: 'ja-JP',
                                preferredCurrency: 'JPY',
                            },
                            {
                                id: 'ko-KR',
                                preferredCurrency: 'KRW',
                            },
                            {
                                id: 'nl-NL',
                                preferredCurrency: 'EUR',
                            },
                            {
                                id: 'pl-PL',
                                preferredCurrency: 'PLN',
                            },
                            {
                                id: 'sv-SE',
                                preferredCurrency: 'SEK',
                            },
                            {
                                id: 'zh-CN',
                                preferredCurrency: 'CNY',
                            },
                            {
                                id: 'zh-TW',
                                preferredCurrency: 'TWD',
                            },
                        ],
                        supportedCurrencies: ['CNY', 'DKK', 'EUR', 'GBP', 'JPY', 'KRW', 'PLN', 'SEK', 'TWD'],
                    },
                    {
                        id: 'RefArch',
                        defaultLocale: 'en-US',
                        defaultCurrency: 'USD',
                        supportedLocales: [
                            {
                                id: 'en-US',
                                preferredCurrency: 'USD',
                            },
                        ],
                        supportedCurrencies: ['USD'],
                    },
                ],
                // Source `sites` from the DAL when the matching Business Manager sync is
                // enabled. On by default; the sites above stay the source of truth whenever
                // the DAL entry is missing, unavailable, or yields no usable sites.
                // Override via PUBLIC__app__commerce__sitesFromDal=false.
                sitesFromDal: true,
            },
            // Global default cookie attributes applied to ALL storefront cookies
            // (auth/session + site-context: site_id, locale, currency). A per-site
            // commerce.sites[].cookies.domain overrides this. Empty string = host-only
            // scoping — setting a cookie domain is an opt-in feature.
            // Override via PUBLIC__app__cookies__domain=.example.com
            //
            // This (and the per-site commerce.sites[].cookies.domain) is the ONLY place to set the
            // cookie domain. DO NOT set a domain on app.siteContext.cookieOptions — it is ignored.
            cookies: { domain: '' },
            // Default site ID configuration
            // See CONFIG-OPTIONS.md#defaultSiteId for detailed documentation
            defaultSiteId: 'RefArchGlobal',
            siteAliasMap: {
                RefArch: 'us',
                RefArchGlobal: 'global',
            },
            // Hybrid mode configuration
            // See CONFIG-OPTIONS.md#hybrid for detailed documentation
            hybrid: {
                enabled: false,
                legacyRoutes: [],
            },
            // Authentication configuration shared across all auth features
            // See CONFIG-OPTIONS.md#auth for detailed documentation
            auth: {
                otpLength: 6,
            },
            // Feature flags for enabling/disabling functionality
            // See CONFIG-OPTIONS.md#features for detailed documentation
            features: {
                passkey: {
                    enabled: false,
                    mode: 'email',
                    callbackUri: '',
                },
                passwordlessLogin: {
                    enabled: false,
                    mode: 'email',
                    callbackUri: '/passwordless-login-callback',
                    landingUri: '/login',
                },
                otpRequest: {
                    mode: 'email',
                    callbackUri: '',
                },
                resetPassword: {
                    mode: 'email',
                    callbackUri: '/reset-password-callback',
                    landingUri: '/reset-password',
                },
                socialLogin: {
                    enabled: true,
                    callbackUri: '/social-callback',
                    providers: ['Apple', 'Google'],
                },
                socialShare: {
                    enabled: true,
                    providers: ['Twitter', 'Facebook', 'LinkedIn', 'Email'],
                },
                guestCheckout: true,
                shopperContext: {
                    enabled: false,
                },
                googleCloudAPI: {
                    apiKey: '',
                },
                mrtBasedPageDesignerResolution: false,
            },
            // Internationalization configuration
            // See CONFIG-OPTIONS.md#i18n for detailed documentation
            // When updating these i18n properties, please also check that the middleware configurations are in sync
            // See src/middlewares/i18next.ts
            // Also, make sure the supportedLngs are always presented in site.supportedLocale to
            // make sure the app can fully be translated to another language
            i18n: {
                fallbackLng: 'en-GB',
                supportedLngs: [
                    'da-DK',
                    'de-DE',
                    'fi-FI',
                    'fr-FR',
                    'it-IT',
                    'ja-JP',
                    'ko-KR',
                    'nl-NL',
                    'pl-PL',
                    'sv-SE',
                    'zh-CN',
                    'zh-TW',
                    'en-US',
                    'en-GB',
                ], // Your supported languages, the fallback should be LAST
            },
            // Global UI configuration and component settings
            // See CONFIG-OPTIONS.md#global for detailed documentation
            global: {
                // TODO: Allow page specific customization while keeping global defaults, e.g.:
                //   config.pages.search.components?.productListing ?? config.global.productListing
                branding: { name: 'Performer', logoAlt: 'Home' },
                productListing: {
                    defaultProductTileImgAspectRatio: 1,
                },
                inventory: { lowStockThreshold: 5 },
                carousel: { defaultItemCount: 4 },
                badges: [
                    { propertyName: 'c_isNew', label: 'New', color: 'green', priority: 1 },
                    { propertyName: 'c_isSale', label: 'Sale', color: 'orange', priority: 2 },
                    { propertyName: 'c_isLimited', label: 'Limited', color: 'purple', priority: 3 },
                    { propertyName: 'c_isExclusive', label: 'Exclusive', color: 'blue', priority: 4 },
                    { propertyName: 'c_isTrending', label: 'Trending', color: 'pink', priority: 5 },
                    { propertyName: 'c_isBestSeller', label: 'Best Seller', color: 'yellow', priority: 6 },
                    { propertyName: 'c_isOutOfStock', label: 'Out of Stock', color: 'red', priority: 7 },
                ],
                skeleton: {
                    thumbnails: 4,
                    colorVariants: 4,
                    sizeVariants: 3,
                    accordionSections: 3,
                    defaultItemCount: 4,
                },
                recommendations: {
                    search_limit: {
                        youMightLike: 8,
                        completeLook: 12,
                        recentlyViewed: 6,
                    },
                    // Static configuration for recommendation types
                    types: {
                        'you-may-also-like': {
                            enabled: true,
                            priority: 1,
                            sort: 'best-matches',
                            titleKey: 'product.recommendations.youMightAlsoLike',
                        },
                        'complete-the-look': {
                            enabled: true,
                            priority: 2,
                            sort: 'price-low-to-high',
                            titleKey: 'product.recommendations.completeTheLook',
                        },
                        'recently-viewed': {
                            enabled: false,
                            priority: 3,
                            sort: 'most-popular',
                            titleKey: 'product.recommendations.recentlyViewed',
                        },
                    },
                },
            },
            // Link hints for browser resource loading
            // See CONFIG-OPTIONS.md#links for detailed documentation
            links: {
                // DIS hosts:
                // - Staging: https://edge.disstg.commercecloud.salesforce.com
                // - Production: https://edge.dis.commercecloud.salesforce.com
                preconnect: [DIS_DEFAULT_HOST],
            },
            // Salesforce Dynamic Imaging Service settings
            // See CONFIG-OPTIONS.md#images for detailed documentation
            // DIS hosts:
            // - Staging: https://edge.disstg.commercecloud.salesforce.com
            // - Production: https://edge.dis.commercecloud.salesforce.com
            images: {
                quality: 70,
                formats: ['webp'],
                fallbackFormat: 'jpg',
                host: DIS_DEFAULT_HOST,
                enableDis: true,
                realmHostMappings: [],
            },
            // Search-specific settings
            // See CONFIG-OPTIONS.md#search for detailed documentation
            search: {
                products: {
                    refine: {
                        orderableOnly: true,
                    },
                    hits: {
                        limit: 24,
                        critical: 4,
                    },
                    // Discrete viewType declarations the storefront uses for product images.
                    // The search filter derives its SCAPI `imgTypes` from these values
                    // (Object.values), so adding a new role here automatically widens the
                    // filter. Must stay aligned with the hardcoded viewTypes in product-image
                    // and product-utils.ts, see docs/README-IMAGES.md.
                    images: {
                        tile: 'medium',
                        swatch: 'swatch',
                    },
                },
            },
            // Performance optimization settings
            // See CONFIG-OPTIONS.md#performance for detailed documentation
            performance: {
                caching: { apiCacheTtl: 300, staticAssetCacheTtl: 31536000 },
                metrics: {
                    serverPerformanceMetricsEnabled: false,
                    serverTimingHeaderEnabled: false,
                    clientPerformanceMetricsEnabled: false,
                },
            },
            // Analytics and engagement adapters — disabled by default in generated
            // projects. No shopper data is sent until you opt in.
            //
            // To send analytics to YOUR Commerce Cloud instance, set `enabled: true`
            // on the adapter(s) below and fill in your own values (replace the
            // placeholders):
            //   einstein:   einsteinId: '<your-einstein-id>', realm: '<your-realm>',
            //               siteId: '<your-site-id>'  (host already defaults to the cquotient prod endpoint)
            //   activeData: host: 'https://<your-instance>.dx.commercecloud.salesforce.com',
            //               siteUUID: '<your-site-uuid>'
            //   data360:    appSourceId: '<your-app-source-id>', tenantId: '<your-tenant-id>',
            //               siteId: '<your-site-id>'
            //
            // Heads up: product recommendation carousels are powered by Einstein. While
            // the einstein adapter is disabled (or not yet configured with your own
            // values), recommendations resolve to empty and those carousels stay hidden.
            //
            // See CONFIG-OPTIONS.md#engagement for the full reference.
            engagement: {
                adapters: {
                    einstein: {
                        enabled: false,
                        // Only fire when the shopper has granted the `analytics` consent
                        // category. With the current binary consent UI this equals
                        // "accepted tracking"; it also future-proofs the adapter for
                        // granular per-category consent.
                        //
                        // Because this adapter requires the `analytics` category, keep
                        // 'analytics' in analytics.trackingConsent.consentCategories below.
                        // If consentCategories is empty the consent layer falls back to
                        // ['necessary'] and this adapter sends nothing (a startup warning is
                        // logged). To send unconditionally, remove this consentCategory line.
                        consentCategory: 'analytics',
                        host: 'https://api.cquotient.com',
                        einsteinId: '',
                        isProduction: false,
                        realm: '',
                        siteId: '',
                        eventToggles: {
                            view_page: true,
                            view_product: true,
                            view_search: true,
                            view_category: true,
                            view_recommender: true,
                            click_product_in_category: true,
                            click_product_in_search: true,
                            click_product_in_recommender: true,
                            cart_item_add: true,
                            checkout_start: true,
                            checkout_step: true,
                            view_search_suggestion: true,
                            click_search_suggestion: true,
                            wishlist_item_added: true,
                            wishlist_item_removed: true,
                            wishlist_viewed: true,
                            wishlist_item_merged: true,
                            wishlist_merged: true,
                        },
                    },
                    data360: {
                        enabled: false,
                        // Gate on the `analytics` consent category (see einstein above).
                        consentCategory: 'analytics',
                        appSourceId: '',
                        tenantId: '',
                        siteId: '',
                        // Distinguishes Storefront Next events from PWA Kit's ('pwa') in the shared DLO.
                        webStoreId: 'sfnext',
                        // PWA Kit parity: only view/impression events are mapped. Cart, checkout,
                        // wishlist, and click events have no Data 360 mapping and ship disabled.
                        eventToggles: {
                            view_page: true,
                            view_product: true,
                            view_search: true,
                            view_category: true,
                            view_recommender: true,
                            click_product_in_category: false,
                            click_product_in_search: false,
                            click_product_in_recommender: false,
                            cart_item_add: false,
                            checkout_start: false,
                            checkout_step: false,
                            view_search_suggestion: false,
                            click_search_suggestion: false,
                            wishlist_item_added: false,
                            wishlist_item_removed: false,
                            wishlist_viewed: false,
                            wishlist_item_merged: false,
                            wishlist_merged: false,
                        },
                    },
                    activeData: {
                        enabled: false,
                        // Gate on the `analytics` consent category (see einstein above).
                        consentCategory: 'analytics',
                        host: '',
                        siteUUID: '',
                        eventToggles: {
                            view_page: true,
                            view_product: true,
                            view_search: true,
                            view_category: true,
                            view_recommender: false,
                            click_product_in_category: false,
                            click_product_in_search: false,
                            click_product_in_recommender: false,
                            cart_item_add: false,
                            checkout_start: false,
                            checkout_step: false,
                            view_search_suggestion: false,
                            click_search_suggestion: false,
                            wishlist_item_added: false,
                            wishlist_item_removed: false,
                            wishlist_viewed: false,
                            wishlist_item_merged: false,
                            wishlist_merged: false,
                        },
                    },
                },
                analytics: {
                    trackingConsent: {
                        enabled: true,
                        defaultTrackingConsent: TrackingConsent.Declined,
                        consentCategories: ['necessary', 'analytics', 'marketing', 'personalization'],
                        position: 'bottom-right',
                    },
                    // Do not send viewPage events for the following paths
                    // We omit /action because we don't want to trigger viewPage events for actions
                    // like modifying the quanity of an item in the cart
                    // We omit /oauth2 and /resource because these do not correspond to pages
                    // We omit /search, /category, /product, and /checkout because they are tracked with
                    // different events (viewSearch, viewCategory, viewProduct, and beginCheckout) triggered
                    // on the search, category, product, and checkout pages respectively
                    pageViewsBlocklist: [
                        '/action',
                        '/oauth2',
                        '/resource',
                        '/search',
                        '/category',
                        '/product',
                        '/checkout',
                    ],
                    // Time in milliseconds before a ViewPage tracked path can be tracked again
                    pageViewsResetDuration: 1500, // 1.5 seconds
                },
            },
            // Development tools and features
            // See CONFIG-OPTIONS.md#development for detailed documentation
            development: { enableDevtools: true, hotReload: true, strictMode: true },
            // Cimulate Agent (Commerce Client messaging widget)
            // Override via PUBLIC__app__cimulateAgent (single JSON string; see src/components/cimulate/README.md).
            cimulateAgent: {
                enabled: '',
                commerceClientScriptSourceUrl: '',
                scrt2Url: '',
                salesforceOrgId: '',
                esDeveloperName: '',
                commerceClientElementId: 'cimulate-messaging-container',
                commerceClientDisplayMode: 'panel' as const,
            },
            // Defaults contributed by installed extensions, auto-discovered from each
            // src/extensions/*/config.ts. Do not edit by hand — regenerate with
            // `pnpm config:aggregate-extensions`. See docs/README-CONFIG.md.
            extension: generatedExtensionConfig,
            // Server-only defaults contributed by installed extensions, auto-discovered from each
            // src/extensions/*/server-config.ts. Reachable on the server via
            // getConfig(context).serverExtension; never serialized into window.__APP_CONFIG__
            // (stripped by src/lib/app-config-client.ts). Do not edit by hand — regenerate with
            // `pnpm config:aggregate-extensions` (the same command that regenerates the client
            // barrel above; one CLI runs both modes). See docs/README-CONFIG.md.
            serverExtension: generatedServerExtensionConfig,
            url: {
                prefix: '/:siteId/:localeId',
                excludeRoutes: ['/resource/**', '/action/**'],
            },
            security: {
                turnstile: {
                    sites: (() => {
                        if (!process.env.PUBLIC__app__security__turnstile__sites) return {};
                        try {
                            return JSON.parse(process.env.PUBLIC__app__security__turnstile__sites);
                        } catch {
                            // oxlint-disable-next-line no-console
                            console.error(
                                '[Turnstile] Failed to parse PUBLIC__app__security__turnstile__sites - no sites configured (fail-closed)'
                            );
                            return {};
                        }
                    })(),
                    enabled: process.env.PUBLIC__app__security__turnstile__enabled === 'true',
                    mode:
                        (process.env.PUBLIC__app__security__turnstile__mode as
                            | 'managed'
                            | 'non-interactive'
                            | 'invisible') || 'managed',
                    verification: {
                        enabled: process.env.TURNSTILE_VERIFICATION_ENABLED === 'true',
                        mode:
                            (process.env.PUBLIC__app__security__turnstile__verification__mode as
                                | 'enforce'
                                | 'log-only'
                                | 'disabled') || undefined,
                    },
                },
                // Security response headers. Default shape is imported from the SDK
                // so customers can override individual fields via PUBLIC__ env vars
                // (e.g. PUBLIC__app__security__headers__csp__reportOnly=true). The
                // SDK middleware merges customer overrides over these defaults.
                //
                // To extend CSP, spread `defaultCspDirectives`:
                //
                //   import { defaultCspDirectives } from '@salesforce/storefront-next-runtime/security';
                //   headers: {
                //     ...defaultSecurityHeaders,
                //     csp: {
                //       directives: {
                //         ...defaultCspDirectives,
                //         'script-src': [...defaultCspDirectives['script-src']!, 'https://cdn.foo.com'],
                //       },
                //       reportOnly: false,
                //     },
                //   },
                //
                // See docs/README-SECURITY-HEADERS.md for the defaults table and recipes.
                headers: defaultSecurityHeaders,
            },
        },
    },
    {
        protectedPaths: [
            'app__engagement__adapters__einstein',
            'app__engagement__adapters__data360',
            // intentionally lock these property at runtime override and allow the rest of config
            'app__engagement__adapters__activeData__enabled',
            'app__engagement__adapters__activeData__eventToggles',
            'app__url__prefix',
            'app__url__excludeRoutes',
        ],
    }
);
