/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Path fragment that marks a module as the server-only extension config barrel. The barrel
 * is `src/extensions/config/server.ts` (auto-generated by `pnpm config:aggregate-extensions`).
 * The two checks in `server-only-config-guard.ts` (`resolveId` and `generateBundle`) both
 * read this fragment so client-side imports are denied at every layer the path can land.
 */
export const SERVER_ONLY_CONFIG_PATH_FRAGMENT = 'src/extensions/config/server';

/**
 * Alias form Vite hands to the resolveId hook before alias resolution. Matches the
 * tsconfig path mapping `@/* -> ./src/*` declared in the template's tsconfig.json,
 * so `@/extensions/config/server` is the same module as `src/extensions/config/server.ts`.
 */
const SERVER_ONLY_CONFIG_ALIAS = '@/extensions/config/server';

/**
 * Suffix the matcher accepts on any tail-form id (`endsWith` against this suffix). Captures
 * the import without `/src/` because the relative form a client module under `src/` would
 * write — `'../../extensions/config/server'` — has no `/src/` segment in its specifier (the
 * specifier is parent-relative, not project-rooted), so anchoring on `/src/extensions/...`
 * would miss it. Vendored packages publishing `node_modules/<pkg>/extensions/config/server.ts`
 * are vanishingly rare and would fail on the `extensions` segment alone if reached.
 */
const PATH_TAIL = 'extensions/config/server';

/**
 * Returns true if the given Vite/Rollup module id refers to the server-only extension
 * config barrel. We compare on a path-tail basis (and also accept the `@/`-aliased form,
 * since `resolveId` runs before alias resolution) rather than the absolute file path so the
 * check is portable across pnpm clones, CI working directories, and Windows-style
 * separators (we normalize backslashes). The matcher accepts every form Rollup may hand to
 * `resolveId`: the alias, the relative parent-rooted path, the absolute resolved path, with
 * or without `.ts` / `.tsx`, and with an optional `?query` suffix Rollup appends in some
 * pipelines.
 *
 * Lives in its own module so unit tests can target the matcher without importing the Vite
 * plugin (`vite` itself transitively boots esbuild's CJS pre-flight, which fails under
 * jsdom on Node 24 — a known cross-realm TextEncoder bug).
 */
export function refersToServerOnlyBarrel(id: string): boolean {
    const normalized = id.replace(/\\/g, '/');
    // Strip a `?query` suffix Rollup may append (e.g. `?import`, `?commonjs-external`)
    // before tail comparisons; presence of the suffix shouldn't change the verdict.
    const withoutQuery = normalized.split('?', 1)[0];
    return (
        withoutQuery === SERVER_ONLY_CONFIG_ALIAS ||
        withoutQuery === `${SERVER_ONLY_CONFIG_ALIAS}.ts` ||
        withoutQuery.endsWith(`/${PATH_TAIL}`) ||
        withoutQuery.endsWith(`/${PATH_TAIL}.ts`) ||
        withoutQuery.endsWith(`/${PATH_TAIL}.tsx`)
    );
}
