/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Custom SCAPI Clients — generated by `sfnext scapi`, do not edit manually.
 *
 * Use `sfnext scapi add --schema <file>` to add a client from a local schema file.
 * Use `sfnext scapi add <family> <name> <version>` to pull from the SCAPI Schemas API.
 * Use `sfnext scapi list` to see registered clients.
 */
export { type Clients as AppClients } from '@salesforce/storefront-next-runtime/scapi';

export const customClients: never[] = [];
