/**
 * Copyright 2026 Salesforce, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Template-local SCAPI barrel — generated by `sfnext scapi`, do not edit manually.
 *
 * Template code should import SCAPI types and clients from `@/scapi` (this file) so
 * that any overrides registered via `sfnext scapi add` resolve to local schemas. With
 * no overrides registered this is a transparent re-export of the runtime SDK.
 */
export * from '@salesforce/storefront-next-runtime/scapi';
export { customClients, type AppClients } from './custom-clients';
